name: Code Quality

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - 'V*'
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
